spring:
  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://124.71.25.233/springBoot
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: never
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    schema:
      - classpath:sql/department.sql
      - classpath:sql/employee.sql
    druid:
      stat-view-servlet:
        allow: all
        login-password: 123456
        login-username: admin
        enabled: true
      web-stat-filter:
        enabled: true
      username: root
      password: 123456
      url: jdbc:mysql://124.71.25.233/springBoot
      initial-size: 5
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #驼峰
    map-underscore-to-camel-case: true

